import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import ReactGA from 'react-ga';
import { useEffect } from 'react';


export default function Home() {

  useEffect(()=>{
    ReactGA.initialize('YOUR_TRACKING_ID');
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/login">go to login page</Link>
    </div>
  )
}
